### PR TITLE
finished needit app

### PR DESCRIPTION
**Pull request by briantgil**
merge

### CODE REVIEW

**Comment by briantgil** [comment]
merged

**Comment by briantgil** [comment]
merged

**Review by briantgil — COMMENTED** [review]
reviewed

**Comment by briantgil** [comment]
closing

**Comment by niedziel** [comment]
Greetings!  It looks like you were testing the Git/Studio integration.  Hopefully you were able to test everything you wanted to.

Just letting you know that you were trying to merge your work into our ServiceNow Dev Site primary student repo rather than into your fork of our repo.  We do not accept pull requests against our primary repo. If you want to access your specific work from a learning module, we recommend that you do not merge the changes into the master branch. If you still want to merge, please select _your fork_ as the base repository in GitHub before making the pull request.

Happy developing!

**Pull request closed without merging**
